# Generated by Django 5.0.3 on 2024-03-09 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_takes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="takes",
            old_name="courses",
            new_name="course",
        ),
    ]
